import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "../components/SessionProvider";
import AdminCheck from "@/components/AdminCheck";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang='en'>
    <body>
      <Provider>
        <AdminCheck />
        <body className={inter.className}>{children}</body>
      </Provider>
    </body>
  </html>
  );
}
